#!/bin/sh

export ROOT=$HOME/inferno64
export SYSHOST=Linux
export OBJTYPE=arm64

case $# in
0) args=sh;;
*) args=$*;;
esac

$ROOT/$SYSHOST/$OBJTYPE/bin/emu -c0 /dis/sh.dis -c "emuwdir=\`{cat /env/emuwdir}; bind -c '#U*'\$emuwdir /n/local; cd /n/local; $args"

